### ISSUE TITLE
Layout exceptions stop the appender

### ISSUE THREAD

**Issue by vy** [vy/log4j2-redis-appender#11]
When the used `Layout` throws an exception, the `RedisAppender` stops working. We have observed this behavior while trying to render `Throwable`s whose stack traces are not printable -- Oh yes! They do exist! Below is the `catalina.out` snippet of a Tomcat that has stopped logging 5 days ago:

```
Exception in thread "AsyncAppender-REDIS_GENERAL_LOG_ASYNC" java.lang.ExceptionInInitializerError
	at com.bol.service.common.binding.ProtoMessage.<clinit>(ProtoMessage.java:4184)
	at com.bol.service.common.binding.ProtoMessage$ServiceError.internalGetFieldAccessorTable(ProtoMessage.java:2398)
	at com.google.protobuf.GeneratedMessage.getDescriptorForType(GeneratedMessage.java:108)
	at com.google.protobuf.TextFormat$Printer.print(TextFormat.java:346)
	at com.google.protobuf.TextFormat$Printer.print(TextFormat.java:336)
	at com.google.protobuf.TextFormat$Printer.printToString(TextFormat.java:603)
	at com.google.protobuf.AbstractMessage.toString(AbstractMessage.java:111)
	at java.lang.String.valueOf(String.java:2994)
	at java.lang.StringBuilder.append(StringBuilder.java:131)
	at com.bol.common.exception.ServerException.toString(ServerException.java:61)
	at java.lang.String.valueOf(String.java:2994)
	at java.lang.StringBuilder.append(StringBuilder.java:131)
	at java.lang.Throwable.printEnclosedStackTrace(Throwable.java:696)
	at java.lang.Throwable.printStackTrace(Throwable.java:668)
	at java.lang.Throwable.printStackTrace(Throwable.java:722)
	at com.vlkan.log4j2.logstash.layout.resolver.StackTraceTextResolver.resolve(StackTraceTextResolver.java:21)
	at com.vlkan.log4j2.logstash.layout.resolver.ExceptionResolver$1.lambda$createStackTraceTextResolver$2(ExceptionResolver.java:49)
	at com.vlkan.log4j2.logstash.layout.resolver.ExceptionResolver.resolve(ExceptionResolver.java:78)
	at com.vlkan.log4j2.logstash.layout.resolver.ExceptionResolver.resolve(ExceptionResolver.java:9)
	at com.vlkan.log4j2.logstash.layout.resolver.TemplateResolvers.lambda$ofObjectNode$5(TemplateResolvers.java:130)
	at com.vlkan.log4j2.logstash.layout.resolver.TemplateResolvers.lambda$ofObjectNode$5(TemplateResolvers.java:130)
	at com.vlkan.log4j2.logstash.layout.resolver.TemplateResolvers.lambda$ofObjectNode$5(TemplateResolvers.java:130)
	at com.vlkan.log4j2.logstash.layout.LogstashLayout.encode(LogstashLayout.java:192)
	at com.vlkan.log4j2.logstash.layout.LogstashLayout.toByteArray(LogstashLayout.java:162)
	at com.vlkan.log4j2.redis.appender.RedisAppender.append(RedisAppender.java:138)
	at org.apache.logging.log4j.core.config.AppenderControl.tryCallAppender(AppenderControl.java:156)
	at org.apache.logging.log4j.core.config.AppenderControl.callAppender0(AppenderControl.java:129)
	at org.apache.logging.log4j.core.config.AppenderControl.callAppenderPreventRecursion(AppenderControl.java:120)
	at org.apache.logging.log4j.core.config.AppenderControl.callAppender(AppenderControl.java:84)
	at org.apache.logging.log4j.core.appender.AsyncAppender$AsyncThread.callAppenders(AsyncAppender.java:454)
	at org.apache.logging.log4j.core.appender.AsyncAppender$AsyncThread.run(AsyncAppender.java:407)
Caused by: java.lang.RuntimeException: Generated message class "com.bol.protojx.xsdtypes.ProtoMessage$Chars" missing method "getValueBytes".
	at com.google.protobuf.GeneratedMessage.getMethodOrDie(GeneratedMessage.java:1973)
	at com.google.protobuf.GeneratedMessage.access$1100(GeneratedMessage.java:61)
	at com.google.protobuf.GeneratedMessage$FieldAccessorTable$SingularStringFieldAccessor.<init>(GeneratedMessage.java:2864)
	at com.google.protobuf.GeneratedMessage$FieldAccessorTable.ensureFieldAccessorsInitialized(GeneratedMessage.java:2110)
	at com.google.protobuf.GeneratedMessage$FieldAccessorTable.<init>(GeneratedMessage.java:2041)
	at com.bol.protojx.xsdtypes.ProtoMessage$1.assignDescriptors(ProtoMessage.java:5404)
	at com.google.protobuf.Descriptors$FileDescriptor.internalBuildGeneratedFileFrom(Descriptors.java:384)
	at com.bol.protojx.xsdtypes.ProtoMessage.<clinit>(ProtoMessage.java:5412)
	... 31 more
Caused by: java.lang.NoSuchMethodException: com.bol.protojx.xsdtypes.ProtoMessage$Chars.getValueBytes()
	at java.lang.Class.getMethod(Class.java:1786)
	at com.google.protobuf.GeneratedMessage.getMethodOrDie(GeneratedMessage.java:1970)
	... 38 more
2020-10-09 09:35:06,249 Log4j2-TF-4-AsyncLoggerConfig-4 ERROR Appender REDIS_GENERAL_LOG_ASYNC is unable to write primary appenders. queue is full
2020-10-09 09:35:06,250 Log4j2-TF-4-AsyncLoggerConfig-4 ERROR Appender REDIS_GENERAL_LOG_ASYNC is unable to write primary appenders. queue is full
2020-10-09 09:35:06,250 Log4j2-TF-4-AsyncLoggerConfig-4 ERROR Appender REDIS_GENERAL_LOG_ASYNC is unable to write primary appenders. queue is full
2020-10-09 09:35:06,250 Log4j2-TF-4-AsyncLoggerConfig-4 ERROR Appender REDIS_GENERAL_LOG_ASYNC is unable to write primary appenders. queue is full
log4j:WARN Disconnect failed to Redis at shd-logbuffer-pro.query.consul:6379
```

**Comment by vy** [comment]
`AsyncAppender` threads only catch `Exception`s, but the thrown exception is of type `Error`. This kills the `AsyncAppender` threads and renders it unusable. The (recommended) fix is to handle these in the `Layout`.
