### ISSUE TITLE
Guava dependency can easily cause issues

### ISSUE THREAD

**Issue by breun** [vy/log4j2-redis-appender#5]
`log4j2-redis-appender` has a dependency on Google Guava, but sadly Guava isn't great a backwards compatibility. When an application depends on `log4j2-redis-appender`, but also has a (possibly transitive) dependency on another Guava version, you can get issues like these on startup:

```
java.lang.ClassNotFoundException: com.google.common.base.MoreObjects
	at org.apache.catalina.loader.WebappClassLoaderBase.loadClass(WebappClassLoaderBase.java:1333)
	at org.apache.catalina.loader.WebappClassLoaderBase.loadClass(WebappClassLoaderBase.java:1167)
	at com.vlkan.log4j2.redis.appender.RedisThrottler.createJmxBeanName(RedisThrottler.java:76)
	at com.vlkan.log4j2.redis.appender.RedisThrottler.<init>(RedisThrottler.java:72)
	at com.vlkan.log4j2.redis.appender.RedisAppender.<init>(RedisAppender.java:86)
	at com.vlkan.log4j2.redis.appender.RedisAppender.<init>(RedisAppender.java:33)
	at com.vlkan.log4j2.redis.appender.RedisAppender$Builder.build(RedisAppender.java:438)
	at com.vlkan.log4j2.redis.appender.RedisAppender$Builder.build(RedisAppender.java:259)
```

In general Guava currently doesn't seem to be great for use in libraries because of the backwards incompatible changes they do.

Luckily as a workaround I can use `log4j2-redis-appender-fatjar` which has its dependencies shaded, but I would still advice libraries to consider not depending on Guava.

**Comment by vy** [comment]
Removed Guava dependency by (hard)copying `RateLimiter`. v0.7 should momentarily appear on Maven Central.
